class CfgWeapons
{
	class Rifle_Base_F;
	class hlc_aug_base: Rifle_Base_F {};
	class hlc_rifle_aug: hlc_aug_base { HIDE_THIS };
	class hlc_rifle_auga1_t: hlc_rifle_aug { SHOW_THIS };
	class hlc_rifle_auga1_b: hlc_rifle_aug { HIDE_THIS };
	class hlc_rifle_auga1carb: hlc_rifle_aug { HIDE_THIS };
	class hlc_rifle_auga1carb_B: hlc_rifle_auga1carb { HIDE_THIS };
	class hlc_rifle_auga1carb_t: hlc_rifle_auga1carb { SHOW_THIS };
	class hlc_rifle_aughbar: hlc_rifle_aug { HIDE_THIS };
	class hlc_rifle_aughbar_B: hlc_rifle_aughbar { HIDE_THIS };
	class hlc_rifle_aughbar_t: hlc_rifle_aughbar { HIDE_THIS };
	class hlc_rifle_augpara: hlc_aug_base { HIDE_THIS };
	class hlc_rifle_augpara_b: hlc_rifle_augpara { HIDE_THIS };
	class hlc_rifle_augpara_t: hlc_rifle_augpara { HIDE_THIS };
	class hlc_rifle_auga2: hlc_rifle_aug { HIDE_THIS };
	class hlc_rifle_auga2_t: hlc_rifle_auga2 { HIDE_THIS };
	class hlc_rifle_auga2_b: hlc_rifle_auga2 { SHOW_THIS };
	class hlc_rifle_augsr: hlc_rifle_auga2 { HIDE_THIS };
	class hlc_rifle_augsr_t: hlc_rifle_augsr { HIDE_THIS };
	class hlc_rifle_augsr_b: hlc_rifle_augsr { HIDE_THIS };
	class hlc_rifle_auga2para: hlc_aug_base { HIDE_THIS };
	class hlc_rifle_auga2para_t: hlc_rifle_auga2para { HIDE_THIS };
	class hlc_rifle_auga2para_b: hlc_rifle_auga2para { HIDE_THIS };
	class hlc_rifle_auga2carb: hlc_rifle_auga2 { HIDE_THIS };
	class hlc_rifle_auga2carb_t: hlc_rifle_auga2carb { HIDE_THIS };
	class hlc_rifle_auga2carb_b: hlc_rifle_auga2carb { SHOW_THIS };
	class hlc_rifle_augsrcarb: hlc_rifle_auga2carb { HIDE_THIS };
	class hlc_rifle_augsrcarb_t: hlc_rifle_augsrcarb { HIDE_THIS };
	class hlc_rifle_augsrcarb_b: hlc_rifle_augsrcarb { HIDE_THIS };
	class hlc_rifle_auga2lsw: hlc_rifle_aughbar { HIDE_THIS };
	class hlc_rifle_auga2lsw_t: hlc_rifle_auga2lsw { HIDE_THIS };
	class hlc_rifle_auga2lsw_b: hlc_rifle_auga2lsw { SHOW_THIS };
	class hlc_rifle_augsrhbar: hlc_rifle_auga2lsw { HIDE_THIS };
	class hlc_rifle_augsrhbar_t: hlc_rifle_augsrhbar { HIDE_THIS };
	class hlc_rifle_augsrhbar_b: hlc_rifle_augsrhbar { HIDE_THIS };
	class hlc_rifle_auga3: hlc_rifle_aug { SHOW_THIS };
	class hlc_rifle_auga3_bl: hlc_rifle_auga3 { HIDE_THIS };
	class hlc_rifle_auga3_b: hlc_rifle_auga3 { SHOW_THIS };
	class hlc_rifle_auga3_GL: hlc_rifle_auga3 { SHOW_THIS };
	class hlc_rifle_auga3_GL_BL: hlc_rifle_auga3_GL { HIDE_THIS };
	class hlc_rifle_auga3_GL_B: hlc_rifle_auga3_GL { SHOW_THIS };
};